# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ID_TOKEN: ${{ secrets.ID_TOKEN }}
  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  SCRIPT_ID: ${{ secrets.SCRIPT_ID }}

on:
  push:
    branches: [ main ]
    paths:
      - '**/**.js'
      - '**/**.tc'
      - '**/**.gs'
jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: sudo npm install

    - name: generate clasprc.json _1
      run: sudo sed -i -e "s/\"access_token\":\"dummy\"/\"access_token\":\"${ACCESS_TOKEN}\"/" clasprc.json

    - name: generate clasprc.json _2
      run: sudo sed -i -e "s/\"id_token\":\"dummy\"/\"id_token\":\"${ID_TOKEN}\"/" clasprc.json

    - name: generate clasprc.json _3
      run: sudo sed -i -e "s/\"clientId\":\"dummy\"/\"clientId\":\"${CLIENT_ID}\"/" clasprc.json

    - name: generate clasprc.json _4
      run: sudo sed -i -e "s/\"clientSecret\":\"dummy\"/\"clientSecret\":\"${CLIENT_SECRET}\"/" clasprc.json

    - name: generate clasprc.json _5
      run: sudo sed -i -e "s@\"refresh_token\":\"dummy\"@\"refresh_token\":\"${REFRESH_TOKEN}\"@" clasprc.json

    - name: generate .clasp.json
      run: |
        sudo sed -i -e "s/\"scriptId\":\"dummy\"/\"scriptId\":\"${SCRIPT_ID}\"/" ./scripts/.clasp.json
  
    - name: set clasprc
      run: sudo cat clasprc.json > ~/.clasprc.json

    - name: test
      run: ls -l
#    - name: push
#      run: sudo npx clasp push --force

#    - name: deploy
#      run: sudo npx clasp deploy
