# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    paths:
      - '**/**.js'
      - '**/**.tc'
      - '**/**.gs'
jobs:
  build:

    environment: PROD
    
    env:
     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
     ID_TOKEN: ${{ secrets.ID_TOKEN }}
     REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
     CLIENT_ID: ${{ secrets.CLIENT_ID }}
     CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
     SCRIPT_ID: ${{ secrets.SCRIPT_ID }}

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install

    - name: generate clasprc.json _1
      run: sed -i -e "s/\"access_token\":\"dummy\"/\"access_token\":\"${ACCESS_TOKEN}\"/" clasprc.json

    - name: generate clasprc.json _2
      run: sed -i -e "s/\"id_token\":\"dummy\"/\"id_token\":\"${ID_TOKEN}\"/" clasprc.json

    - name: generate clasprc.json _3
      run: sed -i -e "s/\"clientId\":\"dummy\"/\"clientId\":\"${CLIENT_ID}\"/" clasprc.json

    - name: generate clasprc.json _4
      run: sed -i -e "s/\"clientSecret\":\"dummy\"/\"clientSecret\":\"${CLIENT_SECRET}\"/" clasprc.json

    - name: generate clasprc.json _5
      run: sed -i -e "s@\"refresh_token\":\"dummy\"@\"refresh_token\":\"${REFRESH_TOKEN}\"@" clasprc.json

    - name: generate .clasp.json
      run: |
        sed -i -e "s/\"scriptId\":\"dummy\"/\"scriptId\":\"${SCRIPT_ID}\"/" .clasp.json
  
    - name: set clasprc
      run: cat clasprc.json > ~/.clasprc.json
      
    - name: push
      run: npm run push

#    - name: deploy
#      run: sudo npx clasp deploy
